#! /usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and

# make-ssl-multicert: generate arbitrary numbers of SSL certificates
# Generate up to $COUNT SSL certificates and the corresponding ssl_multicert.config

OPENSSL=${OPENSSL:-openssl}
COUNT=${COUNT:-100001}

for ((i=0 ; i < $COUNT ; i++)); do
  $OPENSSL genrsa -out test$i.key 2048
  $OPENSSL req -new -key test$i.key -out test$i.csr -subj /C=US/ST=CA/L=Norm/O=TrafficServer/OU=Test/CN=test${i}.com
  $OPENSSL x509 -req -days 365 -in test$i.csr -signkey test$i.key -out test$i.crt
  cat test$i.crt test$i.key > test$i.pem
  rm -rf test$i.csr test$i.key test$i.crt

  echo ssl_cert_name=test$i.pem >> ssl_multicert.config
done
