# Documentation https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
notifications:
  commits: commits@trafficserver.apache.org
  issues: issues@trafficserver.apache.org
  pullrequests: github@trafficserver.apache.org
github:
  description: "Apache Traffic Server™ is a fast, scalable and extensible HTTP/1.1 and HTTP/2 compliant caching proxy server."
  homepage: https://trafficserver.apache.org/
  labels:
    - proxy
    - cdn
    - cache
    - apache
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
  enabled_merge_buttons:
    # Enable squash button:
    squash: true
    # Disable rebase button:
    rebase: false
    # Disable merge button:
    merge: false
