#!/usr/bin/env python

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed
# with this work for additional information regarding copyright
# ownership.  The ASF licenses this file to you under the Apache
# License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain a copy of the
# License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

print '''1..2 shortContentLengthDisconnect
# The proxy sends the right Content-Length header and closes the
# client connection if the origin disconnects before the proxy sends
# the response headers'''

from twisted.internet import error, protocol, reactor, tcp
from twisted.web import http


def callback():
    print 'not ok 2 - The client was left hanging'

    reactor.stop()


reactor.callLater(1, callback)


class factory(http.HTTPFactory):
    class protocol(http.HTTPChannel):
        class requestFactory(http.Request):
            def requestReceived(ctx, method, target, version):

                ctx.client = None
                ctx.clientproto = version

                ctx.setHeader('Content-Length', 29)
                ctx.write('shortContentLengthDisconnect')

                # Disconnect before the proxy sends the response headers
                ctx.transport.loseConnection()


origin = tcp.Port(0, factory())
origin.startListening()

print '# Listening on {0}:{1}'.format(*origin.socket.getsockname())


class factory(protocol.ClientFactory):
    def clientConnectionFailed(ctx, connector, reason):

        print 'Bail out!'
        reason.printTraceback()

        reactor.stop()

    class protocol(http.HTTPClient):
        def connectionLost(ctx, reason):
            try:
                reactor.stop()

            except error.ReactorNotRunning:
                pass

            else:
                print 'ok 2 - The client connection closed'

        def connectionMade(ctx):
            ctx.transport.write('GET {0}:{1} HTTP/1.1\r\n\r\n'.format(*origin.socket.getsockname()))

        def handleHeader(ctx, k, v):
            if k.lower() == 'content-length':
                if v != '29':
                    print 'not',

                    # Who cares what happens now?
                    reactor.stop()

                print 'ok 1 - Content-Length header'

        # Avoid calling undefined handleResponse() at the end of the
        # message (if the proxy sent the wrong Content-Length header).
        # (Override connectionLost() when the proxy closes the client
        # connection or we stop the reactor.)
        def handleResponseEnd(ctx):
            pass


tcp.Connector('localhost', 8080, factory(), 30, None, reactor).connect()

reactor.run()
