#! /usr/bin/env sh

#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# sbuild: trivial sphinx-build wrapper to handle recursive make variable expansion.

SPHINXBUILD="$1"
shift

if [ -z "${PLANTUML_JAR}" ] ; then
  echo 'PLANTUML_JAR' not set.
  exit 1;
elif [ ! -r "${PLANTUML_JAR}" ] ; then
  echo plantuml jar \'${PLANTUML_JAR}\' not readable.
  exit 1;
elif [ ! -f "${PLANTUML_JAR}" ] ; then
  echo plantuml jar \'${PLANTUML_JAR}\' is not actually a jar.
  exit 1;
fi


exec $SPHINXBUILD \
  `eval echo \\$PAPEROPT_$PAPER` \
  "$@"
