.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "config:root"
.SH NAME
config:root \- Switch to root user.
.SH SYNOPSIS
config:root
.SH DESCRIPTION
If you want to become the root user type the config:root command.  
You will be prompted to enter the root password.  The config:root command takes no options.
.SH EXAMPLE 
.TP
.fi
When you execute the config:root command, you see the following:
.PP
.nf
traffic_shell> config:root
Password: (enter password)
traffic_shell#
.SH "SEE ALSO"
enable, disable, exit
