.TH "config:ntlm"
.SH NAME
config:ntlm \- Configures NTLM access control.
.SH SYNOPSIS
config:ntlm [options]
.SH DESCRIPTION
The config:ntlm command enables you to configure NTLM access control
through a variety of options. You must use one of the options described below.
.SH OPTIONS
The following options are supported for the config:ntlm command:
.SS "status <on | off>"
Enables (on) or disables (off) the proxy from serving NTLM requests.
.SS "domain-controller <string>"
Specifies the comma separated list of domain controller hostnames.
.SS "nt-domain <string>"
Specifies the NT domain name that the proxy should authenticate against.
.SS "load-balancing <on | off>"
Enables (on) or disables (off) the load balancing of requests to domain controllers.
.SH EXAMPLES
.SS "Example 1. Enabling the proxy to serve NTLM requests"
.PP
.nf
traffic_shell> config:ntlm status on
traffic_shell> 
.SS "Example 2. Specifying multiple domain controllers"
.PP
.nf
traffic_shell> config:ntlm domain-controller "machine1.example.com, machine2.example.com"
traffic_shell> 
.SH "SEE ALSO"
show:ntlm, show:ntlm-stats
