.TH "config:stop"
.SH NAME
config:stop \- Stops the proxy software.
.SH SYNOPSIS
config:stop
.SH DESCRIPTION
The config:stop command stops your proxy software. The config:stop command takes 
no options. 
.SH EXAMPLES
When you execute the config:stop command, you see results in the following format.
.PP
.nf
traffic_shell> config:stop
traffic_shell>
.SH "SEE ALSO"
config:start, config:restart, config:hard-restart
