.TH "config:start"
.SH NAME
config:start \- Starts the proxy software.
.SH SYNOPSIS
config:start
.SH DESCRIPTION
The config:start command starts your proxy software. The config:start command 
takes no options. 
.SH EXAMPLES
When you execute the config:start command, you see results in the following 
format:
.PP
.nf
traffic_shell> config:start
traffic_shell>
.SH "SEE ALSO"
config:stop, config:restart, config:hard-restart
