.TH "config:restart"
.SH NAME
config:restart \- Restarts the proxy software.
.SH SYNOPSIS
config:restart [options]
.SH DESCRIPTION
The config:restart command restarts your proxy software. When you execute the
config:restart command, you may use one of the options described below.
.SS "cluster"
Specifies cluster-wide restart.
.SH EXAMPLES
When you execute the config:restart command, you see results in the following format.
.PP
.nf
traffic_shell> config:restart
traffic_shell>
.SH "SEE ALSO"
config:start, config:stop, config:hard-restart
