.TH "config:root"
.SH NAME
config:root \- Switch to root user.
.SH SYNOPSIS
config:root
.SH DESCRIPTION
If you want to become the root user type the config:root command.  
You will be prompted to enter the root password.  The config:root command takes no options.
.SH EXAMPLE 
.TP
.fi
When you execute the config:root command, you see the following:
.PP
.nf
traffic_shell> config:root
Password: (enter password)
traffic_shell#
.SH "SEE ALSO"
enable, disable, exit
