.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "config:snmp"
.SH NAME
config:snmp \- Enables SNMP.
.SH SYNOPSIS
config:snmp status [on | off]
.SH DESCRIPTION
You use the config:snmp command to enable or disable the SNMP agent.
.SH OPTIONS
The following option is supported for the config:snmp command:
.SS "status <on | off>"
Enables (on) or disables (off) the SNMP agent. (The default value is on.)
.SH EXAMPLES
.SS "Example 1. Enabling SNMP"
.PP
.nf
traffic_shell> config:snmp on 
traffic_shell>
.SH "SEE ALSO"
show:snmp
