.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "config:restart"
.SH NAME
config:restart \- Restarts the proxy software.
.SH SYNOPSIS
config:restart [options]
.SH DESCRIPTION
The config:restart command restarts your proxy software. When you execute the
config:restart command, you may use one of the options described below.
.SS "cluster"
Specifies cluster-wide restart.
.SH EXAMPLES
When you execute the config:restart command, you see results in the following format.
.PP
.nf
traffic_shell> config:restart
traffic_shell>
.SH "SEE ALSO"
config:start, config:stop, config:hard-restart
