.TH "config:name"
.SH NAME
config:name \- Sets the name of the proxy.
.SH SYNOPSIS
config:name [hostname]
.SH DESCRIPTION
The config:name command enables you to set the name of your proxy system. 
.SH OPERANDS
The following operand is supported:
.SS "<proxyname>"
The hostname is your name for your proxy system.
.SH EXAMPLES
.SS "When you execute the config:name command, you see "
.SS "results in the following format:"
.PP
.nf
traffic_shell> config:name somename
somename.yourdomain.com
traffic_shell> 
.SH "SEE ALSO"
show:network
