.TH "config:reset-stats"

.SH NAME

config:reset-stats \- Resets all statistics.

.SH SYNOPSIS

config:reset-stats

.SH DESCRIPTION

The config:reset-stats command resets all statistics. (See the "See Also" 
section below for a list of commands that display statistics.) The config:reset-
stats command takes no options. 

.SH EXAMPLES

.TP

When you execute the config:reset-stats command, you see results in the 
following format:

.TP
ts_shell>config:reset-stats
  +OK
ts_shell>

.SH "SEE ALSO"
show:cache-stats, show:dns-stats, show:hostdb-stats, show:http-stats, show:nntp-
stats, show:ftp-stats, show:proxy-stats, show:http-trans-stats, show:icp-stats, 
show:logging-stats
