.TH "disable"
.SH NAME
disable \- Disable privileged commands.
.SH SYNOPSIS
disable
.SH DESCRIPTION
If you are in Configure mode and want to return to Monitor mode, type 
the disable command. The disable command has no options.
.SH EXAMPLE 
.TP
.fi
When you execute the disable command, you see the following:
.PP
.nf
traffic_shell> disable
traffic_shell>
.SH "SEE ALSO"
enable, config:root, exit
