.TH "exit"
.SH NAME
exit \- Type exit to end your CLI session.
.SH SYNOPSIS
exit
.SH DESCRIPTION
Use the exit command while in show or configure mode to end your CLI 
session. After you use the exit command, you return to your normal UNIX 
prompt. The exit command has no options.
.SH EXAMPLE 
.PP
.fi
When you execute the exit command, you see results in the following format:
.PP
traffic_shell> exit
.TP
[username@hostname bin]#
.SH "SEE ALSO"
enable, disable
