.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "exit"
.SH NAME
exit \- Type exit to end your CLI session.
.SH SYNOPSIS
exit
.SH DESCRIPTION
Use the exit command while in show or configure mode to end your CLI 
session. After you use the exit command, you return to your normal UNIX 
prompt. The exit command has no options.
.SH EXAMPLE 
.PP
.fi
When you execute the exit command, you see results in the following format:
.PP
traffic_shell> exit
.TP
[username@hostname bin]#
.SH "SEE ALSO"
enable, disable
