.TH "show:status"
.SH NAME
show:status \- This command shows you whether the proxy is running.
.SH SYNOPSIS
show:status
.SH DESCRIPTION
If you want confirmation that the proxy is running, use the show:status command. 
The show:status command has no arguments.
.SH EXAMPLE 
.SS "When you execute the show:status command, you see the "
.SS "following if the proxy is on."
.PP
.nf
traffic_shell> show:status
Proxy -- on
traffic_shell>
.SH "SEE ALSO"
show:proxy, show:proxy-stats, show:cache-stats, config:reset-stats
