.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "show:hostdb-stats"
.SH NAME
show:hostdb-stats \- This command displays host database statistics.
.SH SYNOPSIS
show:hostdb-stats
.SH DESCRIPTION
The show:hostdb-stats command displays host database statistics, including hit 
rate and DNS lookup detail. The show:hostdb-stats command takes no options.
.SH EXAMPLE
.PP
When you execute the show:hostdb-stats command, you see results in the following format:
.PP
.nf
traffic_shell> show:hostdb-stats
Host Database hit Rate -- 99.988437%I    *
DNS Lookups Per Second -- 0.000000
* Value reprensents 10 second average.
traffic_shell>
.SH "SEE ALSO"
config:hostdb
