.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "show:alarms"
.SH NAME
show:alarms \- This command displays information about active alarms.
.SH SYNOPSIS
show:alarms
.SH DESCRIPTION
The show:alarms command displays a list of active alarms.  
The show:alarms command takes no options.
.SH EXAMPLE
When you execute the show:alarms command, you see results in the following format:
.PP
.nf
traffic_shell> show:alarm
Active Alarms
  1. MGMT_ALARM_PROXY_PROCESS_DIED
traffic_shell> 
.SH "SEE ALSO"
config:alarms
