.TH "show:ssl"
.SH NAME
show:ssl \- This command displays SSL port configuration.
.SH SYNOPSIS
show:ssl
.SH DESCRIPTION
The show:ssl command displays SSL port configuration information. The show:ssl 
command takes no options.
.SH EXAMPLE
.SS "When you execute the show:ssl command, you see results in the"
.SS "following format"
.PP
.nf
traffic_shell> show:ssl
Restrict SSL Connections to Ports -- 443 563
traffic_shell>
.SH "SEE ALSO"
config:ssl
