.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "show:ldap-stats"
.SH NAME
show:ldap-stats \- This command displays LDAP protocol statistics.
.SH SYNOPSIS
show:ldap-stats
.SH DESCRIPTION
The show:ldap-stats command displays LDAP protocol statistics, including
cache hits, cache misses, server errors, and authorization statistics. 
The show:ldap-stats command takes no options.
.SH EXAMPLE
.PP
When you execute the show:ldap-stats command, you see results in the following format:
.PP
.nf
traffic_shell> show:ldap-stats 
Cache Hits---------------- 0
Cache Misses-------------- 0
Server Errors------------- 0
Authorization Denied------ 0
Authorization Timeouts---- 0
Authorization Cancelled--- 0
traffic_shell>
.SH "SEE ALSO"
show:ldap, config:ldap
