.TH "show:proxy"
.SH NAME
show:proxy \- This command displays the proxy name.
.SH SYNOPSIS
show:proxy
.SH DESCRIPTION
Execute the show:proxy command to see the name of the proxy. The show:proxy 
command takes no options.
.SH EXAMPLE 
When you execute the show:proxy command, you see results in the following format:
.PP
.nf
traffic_shell> show:proxy
Name -- rubicon
traffic_shell>
.SH "SEE ALSO"
show:proxy-stats
