.TH "show:dns-stats"
.SH NAME
show:dns-stats \- This command displays DNS statistics.
.SH SYNOPSIS
show:dns-stats
.SH DESCRIPTION
The show:dns-stats command displays DNS statistics, including DNS lookup detail. 
The show:dns-stats command takes no options.
.SH EXAMPLE
.PP
When you execute the show:dns-stats command, you see results in the following 
format:
.PP
.nf
traffic_shell> show:dns-stats
DNS Lookups Per Second -- 0.000000
traffic_shell>
.SH "SEE ALSO"
config:dns
