.TH "show:virtual-ip"
.SH NAME
show:virtual-ip \- This command displays virtual IP configuration information
.SH SYNOPSIS
show:virtual-ip
.SH DESCRIPTION
The show:virtual-ip command displays the virtual IP addresses configured for 
your system. The show:virtual-ip command takes no options.
.SH EXAMPLE
.SS "When you execute the show:virtual-ip command, you see results"
.SS "in the following format."
.PP
.nf
traffic_shell> show:virtual-ip 
  2 Elements in Record
  0 1.1.1.1 23 23
  1 1.1.1.1 23 24
traffic_shell>
.SH "SEE ALSO"
config:virtual-ip
