.TH "show:snmp"
.SH NAME
show:snmp \- This command displays SNMP configuration.
.SH SYNOPSIS
show:snmp
.SH DESCRIPTION
The show:snmp command displays SNMP configuration information, specifying 
whether the SNMP Agent is enabled. The show:snmp command takes no options.
.SH EXAMPLE
When you execute the show:snmp command, you see results in the following format:
.PP
.nf
traffic_shell> show:snmp
SNMP Agent -- on
traffic_shell>
.SH "SEE ALSO"
config:snmp
