.TH "show:ntlm"
.SH NAME
show:ntlm \- This command displays NTLM authentication configuration.
.SH SYNOPSIS
show:ntlm
.SH DESCRIPTION
The show:ntlm command displays NTLM configuration information, including domain
controllers, and NT domain.  The show:ntlm command takes no options.
.SH EXAMPLE
.PP
When you execute the show:ntlm command, you see results in the following format:
.PP
.nf
traffic_shell> show:ntlm
NTLM Authentication ------ on
Domain Controller(s) ----- NULL
NT Domain ---------------- NULL
Load Balancing ----------- off
traffic_shell>
.SH "SEE ALSO"
config:ntlm, show:ntlm-stats
