.TH "show:qt"
.SH NAME
show:qt \- This command displays Quicktime protocol configuration.
.SH SYNOPSIS
show:qt
.SH DESCRIPTION
The show:qt command displays Quicktime protocol configuration information,
such as port numbers.  The show:qt command takes no options.
.SH EXAMPLE
.PP
When you execute the show:qt command, you see results in the following format:
.PP
.nf
traffic_shell> show:qt
Quicktime ------------ on
Proxy port ----------- 554
Monitor Name --------- NULL
Monitor Port --------- 10088
Media Bridge Name ---- NULL
Media Bridge Port ---- 10036
Media Bridge Mount --- ffnet
traffic_shell> 
.SH "SEE ALSO"
config:qt, show:qt-stats
