.TH "show:dns-resolver"
.SH NAME
show:dns-resolver \- This command displays DNS Resolver configuration 
information.
.SH SYNOPSIS
show:dns-resolver
.SH DESCRIPTION
The show:dns-resolver command displays the DNS Resolver configuration 
information, including local domain expansion configuration (see example below). 
The show:dns-resolver command takes no options.
.SH EXAMPLE
.PP
When you execute the show:dns-resolver command, you see results in the following 
format:
.PP
.nf
traffic_shell> show:dns-resolver
Local Domain Expansion -- on
 .com Domain Expansion --- on
traffic_shell>
.SH "SEE ALSO"
config:dns
