.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "show:qt-stats"
.SH NAME
show:qt-stats \- This command displays Quicktime protocol statistics.
.SH SYNOPSIS
show:qt-stats
.SH DESCRIPTION
The show:qt-stats command displays Quicktime protocol statistics, including 
downstream and upstream bytes, client/server connections, and live streams.
The show:qt-stats command takes no options.
.SH EXAMPLE
.PP
When you execute the show:qt-stats command, you see results in the following format:
.PP
.nf
traffic_shell> show:qt-stats
Quicktime:
Downstream Request Bytes ---------- 0
Downstream Response Bytes --------- 0
Upstream Request Bytes ------------ 0
Upstream Response Bytes ----------- 0
Client Connections ---------------- 0
Server Connections ---------------- 0
Unique Live Streams --------------- 0
Cache Bytes Read ------------------ 0
Cache Cutoff ---------------------- 1048576
traffic_shell>
.SH "SEE ALSO"
config:qt, show:qt
