.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.TH "show:logging-stats"
.SH NAME
show:logging-stats \- This command displays logging statistics.
.SH SYNOPSIS
show:logging-stats
.SH DESCRIPTION
The show:logging-stats command displays logging statistics, including storage, 
events logged, and events skipped. The show:logging-stats command takes no 
options.
.SH EXAMPLE
.PP
When you execute the show:logging-stats command, you see results in the 
following format:
.PP
.nf
traffic_shell> show:logging-stats
Current Open Log Files ----------- 0
Space Used For Log Files --------- 13697
Number of Access Events Logged --- 0
Number of Access Events Skipped -- 0
Number of Error Events Logged ---- 0
traffic_shell>
.SH "SEE ALSO"
config:logging
