.\"  Licensed to the Apache Software Foundation (ASF) under one .\"
.\"  or more contributor license agreements.  See the NOTICE file .\"
.\"  distributed with this work for additional information .\"
.\"  regarding copyright ownership.  The ASF licenses this file .\"
.\"  to you under the Apache License, Version 2.0 (the .\"
.\"  "License"); you may not use this file except in compliance .\"
.\"  with the License.  You may obtain a copy of the License at .\"
.\" .\"
.\"      http://www.apache.org/licenses/LICENSE-2.0 .\"
.\" .\"
.\"  Unless required by applicable law or agreed to in writing, software .\"
.\"  distributed under the License is distributed on an "AS IS" BASIS, .\"
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. .\"
.\"  See the License for the specific language governing permissions and .\"
.\"  limitations under the License. .\"
.Dd January 22, 2012
.Dt TRAFFIC.ShELL 1
.sp
.Sh NAME
.Nm traffic_shell
.Nd Traffic Server configuration shell
.sp
.Sh SYNOPSIS
.Nm
.Op Fl V
.Op Ar filename
.sp
.Sh DESCRIPTION
.Nm
is a command-line interface to monitor and configure Apache Traffic Server.
.Nm
enables you to monitor and configure Traffic Server using a
UNIX shell-like command interface.  Using
.Nm
is an alternative to manually editing Traffic Server's configuration
files or using the
.Xr traffic_line 1
interface.
.Pp
You use
.Nm
interactively by typing individual commands at the
.Li trafficserver>
prompt. As you enter a command,
.Nm
processes it
and displays the result.
.Nm
embeds a Tcl interpreter, so you can use the Tcl language to display status or
make configuration changes programmatically.
.Pp
When invoked with the
.Ar filename
argument,
.Nm
will read and execute commands from the given file prior to entering interactive
mode.
.sp
.Sh USING TRAFFIC SHELL COMMANDS
Once you start
.Nm
, you use one of two modes:
.Pp
The Monitor mode allows you to run Show commands, which display system
information and Traffic Server statistics. You use Show commands to monitor
Traffic Server performance. When you start
.Nm ,
you are automatically in Monitor mode.
.Pp
To see a list of Show commands, type
.Sq show
at the prompt. To use a Show command, enter the command at the
.Li trafficserver>
prompt.
.Pp
The Enable mode allows you to run Config commands, which set Traffic Server
and network parameters. The Enable mode is password-protected. To enter Enable
mode use the
.Sq enable
command.
.Pp
You must enter Enable mode to use Config commands. You can use both
Show and Config commands when you are in Enable mode. It is not
necessary to return to Monitor mode to use Show commands.
.Pp
Once you enter Enable mode, you can use the Config commands.  To
see a list of Config commands, type
.Sq config
at the
.Li trafficserver>
prompt. To use a Config command, enter the command at the prompt.
.Pp
To return to Monitor mode, in which you cannot use Config commands to
set parameters, use the
.Sp disable
command.
.Pp
Type
.Sq exit
at the
.Li trafficserver>
prompt to exit
.Nm .
.sp
.Sh TRAFFIC SHELL COMMAND SHORTCUTS
.Nm
supports the following shortcuts for entering commands.
.Bl -bullet
.It
Command completion. Type the initial characters of a valid command, and then
press the tab key. Traffic Shell completes the command.
.It
Command abbreviation. Type the initial characters of a valid command, and then
press the Enter key.
.Nm
displays all commands that begin with the characters that you
enter. If only one command begins with those characters,
.Nm
immediately executes that command.
.It
Command history. From the
.Li trafficserver>
prompt, press the Up and Down arrow keys to scroll
through commands that you previously entered.
.El
.sp
.Sh ACCESSING ON-LINE HELP
.Nm
includes manual pages that describe each command.  To access
.Nm
's man pages, type
.Sq help ,
followed by any
.Nm
command at the prompt.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl V
Print version information and exit.
.El
.sp
.Sh EXAMPLES
Displaying the on-line help for a command:
.Bd -ragged -offset 12345678
trafficserver> help show:security
.Ed
.Pp
Use a monitor command to show a Traffic Server configuration setting:
.Bd -ragged -offset 12345678
trafficserver> show:http
.Ed
.Pp
Use a config command to alter a Traffic Server configuration setting:
.Bd -ragged -offset 12345678
trafficserver> config:icp multicast on
.Ed
.Pp
Use a Tcl command to show multiple configuration parameters:
.Bd -ragged -offset 12345678
trafficserver> foreach i {http proxy socks ssl} {show:$i}
.Ed
.sp
.Sh SEE ALSO
.Xr traffic_line 1 ,
.Xr Tcl n .
