#!/usr/bin/env python3
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""hrw4u-ir - Inspect HRW4U intermediate representations (CST, AST, ...)."""

from __future__ import annotations

import argparse
import pprint
import sys
from typing import Any, Callable

from antlr4 import CommonTokenStream, InputStream

from hrw4u.ast_builder import ASTBuilder
from hrw4u.hrw4uLexer import hrw4uLexer
from hrw4u.hrw4uParser import hrw4uParser


def emit_cst(tree: Any, parser: hrw4uParser) -> None:
    print(tree.toStringTree(recog=parser))


def emit_ast(tree: Any, parser: hrw4uParser) -> None:
    ast = ASTBuilder().visit(tree)
    pprint.pp(ast, sort_dicts=False)


# Stage registry. Adding a new stage (ast-resolved, ast-validated, ...)
# is a one-line addition here plus its emit_* function above.
STAGES: dict[str, Callable[[Any, hrw4uParser], None]] = {
    "cst": emit_cst,
    "ast": emit_ast,
}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Inspect HRW4U intermediate representations.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Stages:\n"
        "  cst  ANTLR concrete syntax tree (raw parse tree)\n"
        "  ast  dataclass AST built by ASTBuilder\n")
    parser.add_argument(
        "input_file",
        nargs="?",
        type=argparse.FileType("r"),
        default=sys.stdin,
        help="HRW4U source file (default: stdin)")
    parser.add_argument(
        "--stage",
        choices=sorted(STAGES.keys()),
        required=True,
        help="Which IR stage to emit (required)")
    args = parser.parse_args()

    content = args.input_file.read()
    if args.input_file is not sys.stdin:
        args.input_file.close()

    token_stream = CommonTokenStream(hrw4uLexer(InputStream(content)))
    antlr_parser = hrw4uParser(token_stream)
    tree = antlr_parser.program()

    if antlr_parser.getNumberOfSyntaxErrors() > 0:
        print("Parse failed: syntax errors above.", file=sys.stderr)
        return 1

    STAGES[args.stage](tree, antlr_parser)
    return 0


if __name__ == "__main__":
    sys.exit(main())
