/**
 * @file CompileParseRules.cc
 *
 * @brief Build-time utility for generating ParseRules character classification tables.
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This standalone C++ program generates static lookup tables used by the
 * Traffic Server runtime for O(1) character classification and case conversion.
 * It is executed during the build process and is **not part of the runtime library**.
 *
 * The generated tables are written to the following files:
 *   - @c gParseRulesCType: Bitmask of character type flags (32-bit values).
 *   - @c gParseRulesCTypeToUpper: Uppercase conversion table (uint8_t values).
 *   - @c gParseRulesCTypeToLower: Lowercase conversion table (uint8_t values).
 *
 * These files are typically included as static data in @c ParseRules.cc.
 *
 * @note This tool uses modern C++ features, including:
 *       - @c std::string for type-safe string handling.
 *       - @c std::ofstream for RAII-based file I/O.
 *       -  Fixed-width integer types (@c uint8_t, @c uint32_t) for portability.
 *
 * @see ParseRules.h for character classification function declarations.
 * @see ParseRules.cc for runtime usage of generated tables.
 */

#include <cstdint>
#include <cstdio>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

#include "tscore/ParseRules.h"

/**
 * @brief Placeholder for the character type bitmask table.
 *
 * This array is initialized to zero and serves as a template for the generated
 * @c gParseRulesCType table. It is **not used at runtime**.
 *
 * @note The actual populated table is generated by @c main() and written to
 *       the @c gParseRulesCType file.
 */
const uint32_t gParseRulesCType[256] = {0};

/**
 * @brief Placeholder for the uppercase conversion table.
 *
 * This array is initialized to zero and serves as a template for the generated
 * @c gParseRulesCTypeToUpper table. It is **not used at runtime**.
 *
 * @note The actual populated table is generated by @c main() and written to
 *       the @c gParseRulesCTypeToUpper file.
 */
const uint8_t gParseRulesCTypeToUpper[256] = {0};

/**
 * @brief Placeholder for the lowercase conversion table.
 *
 * This array is initialized to zero and serves as a template for the generated
 * @c gParseRulesCTypeToLower table. It is **not used at runtime**.
 *
 * @note The actual populated table is generated by @c main() and written to
 *       the @c gParseRulesCTypeToLower file.
 */
const uint8_t gParseRulesCTypeToLower[256] = {0};

/**
 * @brief Working array for character type bitmasks.
 *
 * Temporary storage for computed character classification bitmasks.
 * Populated by @c main() and written to the @c gParseRulesCType output file.
 *
 * @note Each entry is a 32-bit bitmask where each bit represents a character
 *       classification (e.g., @c is_alpha_BIT, @c is_digit_BIT).
 */
uint32_t gTparseRulesCType[256];

/**
 * @brief Working array for uppercase character conversion.
 *
 * Temporary storage for uppercase character mappings (0-255).
 * Populated by @c main() and written to the @c gParseRulesCTypeToUpper output file.
 */
uint8_t gTparseRulesCTypeToUpper[256];

/**
 * @brief Working array for lowercase character conversion.
 *
 * Temporary storage for lowercase character mappings (0-255).
 * Populated by @c main() and written to the @c gParseRulesCTypeToLower output file.
 */
uint8_t gTparseRulesCTypeToLower[256];

/**
 * @brief Convert a 32-bit unsigned integer to its binary string representation.
 *
 * Creates a 32-character string representing the binary value of the input,
 * with leading zeros. The string is in **big-endian format** (MSB first).
 *
 * @param u The 32-bit unsigned integer to convert.
 * @return @c std::string containing the 32-character binary representation.
 *         Example: @c UintToBinary(5) returns @c "00000000000000000000000000000101".
 *
 * @note This function is **thread-safe** because it returns a new @c std::string
 *       by value (no shared static buffer).
 */
std::string
UintToBinary(uint32_t u)
{
  std::string buf(32, '0');
  for (uint8_t i = 0; i < 32; i++) {
    if (u & (1U << (31 - i))) {
      buf[i] = '1';
    }
  }
  return buf;
}

/**
 * @brief Generates character classification lookup tables.
 *
 * This function performs the following steps:
 *
 * 1. For each ASCII character (0-255):
 *    - Initializes the working arrays (@c gTparseRulesCType, @c gTparseRulesCTypeToUpper,
 *      @c gTparseRulesCTypeToLower).
 *    - Tests the character against all @c ParseRules classification functions.
 *    - Sets the corresponding bit in @c gTparseRulesCType[i] for each matching classification.
 *    - Stores the uppercase/lowercase conversion values in @c gTparseRulesCTypeToUpper
 *      and @c gTparseRulesCTypeToLower.
 *
 * 2. Writes three output files using @c std::ofstream (RAII):
 *    - @c gParseRulesCType: Contains hexadecimal bitmask values and their binary
 *      representations. Format: C-style array initialization.
 *    - @c gParseRulesCTypeToUpper: Contains uppercase conversion values for each
 *      character. Format: @c (uint8_t)X,
 *    - @c gParseRulesCTypeToLower: Contains lowercase conversion values for each
 *      character. Format: @c (uint8_t)X,
 *
 * @return 0 on successful completion.
 *
 * @note The classification functions from @c ParseRules.h include:
 *       - **Character types**: @c IsChar, @c IsAlpha, @c IsDigit, @c IsAlnum,
 *         @c IsCtl, @c IsWs, @c IsHex, @c IsPchar, @c IsToken, @c IsUri,
 *         @c IsSep, @c IsEmpty.
 *       - **Case types**: @c IsUpalpha, @c IsLoalpha.
 *       - **Safety/encoding**: @c IsSafe, @c IsUnsafe, @c IsReserved,
 *         @c IsUnreserved, @c IsNational.
 *       - **Special categories**: @c IsPunct, @c IsTspecials, @c IsEndOfUrl.
 *       - **Whitespace variants**: @c IsSpcr, @c IsSplf, @c IsWslfcr, @c IsEow.
 *       - **HTTP/MIME**: @c IsHttpFieldName, @c IsHttpFieldValue,
 *         @c IsMimeSep, @c IsControl.
 *
 * @see ParseRules.h for detailed descriptions of each classification function.
 * @see ParseRules.cc for runtime usage of the generated tables.
 */
int
main()
{
  for (uint16_t i = 0; i < 256; i++) {
    gTparseRulesCType[i]        = 0;
    gTparseRulesCTypeToLower[i] = static_cast<uint8_t>(ParseRules::ink_tolower(i));
    gTparseRulesCTypeToUpper[i] = static_cast<uint8_t>(ParseRules::ink_toupper(i));

    if (ParseRules::IsChar(index)) {
      gTparseRulesCType[index] |= IS_CHAR_BIT;
    }
    if (ParseRules::IsUpalpha(index)) {
      gTparseRulesCType[index] |= IS_UPALPHA_BIT;
    }
    if (ParseRules::IsLoalpha(index)) {
      gTparseRulesCType[index] |= IS_LOALPHA_BIT;
    }
    if (ParseRules::IsAlpha(index)) {
      gTparseRulesCType[index] |= IS_ALPHA_BIT;
    }
    if (ParseRules::IsDigit(index)) {
      gTparseRulesCType[index] |= IS_DIGIT_BIT;
    }
    if (ParseRules::IsCtl(index)) {
      gTparseRulesCType[index] |= IS_CTL_BIT;
    }
    if (ParseRules::IsWs(index)) {
      gTparseRulesCType[index] |= IS_WS_BIT;
    }
    if (ParseRules::IsHex(index)) {
      gTparseRulesCType[index] |= IS_HEX_BIT;
    }

    unsigned char cc = static_cast<unsigned char>(i);

    if (ParseRules::IsPchar(&currentChar)) {
      gTparseRulesCType[index] |= IS_PCHAR_BIT;
    }
    if (ParseRules::IsExtra(index)) {
      gTparseRulesCType[index] |= IS_EXTRA_BIT;
    }
    if (ParseRules::IsSafe(index)) {
      gTparseRulesCType[index] |= IS_SAFE_BIT;
    }
    if (ParseRules::IsUnsafe(index)) {
      gTparseRulesCType[index] |= IS_UNSAFE_BIT;
    }
    if (ParseRules::IsNational(index)) {
      gTparseRulesCType[index] |= IS_NATIONAL_BIT;
    }
    if (ParseRules::IsReserved(index)) {
      gTparseRulesCType[index] |= IS_RESERVED_BIT;
    }
    if (ParseRules::IsUnreserved(index)) {
      gTparseRulesCType[index] |= IS_UNRESERVED_BIT;
    }
    if (ParseRules::IsPunct(index)) {
      gTparseRulesCType[index] |= IS_PUNCT_BIT;
    }
    if (ParseRules::IsEndOfUrl(index)) {
      gTparseRulesCType[index] |= IS_END_OF_URL_BIT;
    }
    if (ParseRules::IsTspecials(index)) {
      gTparseRulesCType[index] |= IS_TSPECIALS_BIT;
    }
    if (ParseRules::IsSpcr(index)) {
      gTparseRulesCType[index] |= IS_SPCR_BIT;
    }
    if (ParseRules::IsSplf(index)) {
      gTparseRulesCType[index] |= IS_SPLF_BIT;
    }
    if (ParseRules::IsWslfcr(index)) {
      gTparseRulesCType[index] |= IS_WSLFCR_BIT;
    }
    if (ParseRules::IsEow(index)) {
      gTparseRulesCType[index] |= IS_EOW_BIT;
    }
    if (ParseRules::IsToken(index)) {
      gTparseRulesCType[index] |= IS_TOKEN_BIT;
    }
    if (ParseRules::IsUri(index)) {
      gTparseRulesCType[index] |= IS_URI_BIT;
    }
    if (ParseRules::IsSep(index)) {
      gTparseRulesCType[index] |= IS_SEP_BIT;
    }
    if (ParseRules::IsEmpty(index)) {
      gTparseRulesCType[index] |= IS_EMPTY_BIT;
    }
    if (ParseRules::IsAlnum(index)) {
      gTparseRulesCType[index] |= IS_ALNUM_BIT;
    }
    if (ParseRules::IsSpace(index)) {
      gTparseRulesCType[index] |= IS_SPACE_BIT;
    }
    if (ParseRules::IsControl(index)) {
      gTparseRulesCType[index] |= IS_CONTROL_BIT;
    }
    if (ParseRules::IsMimeSep(index)) {
      gTparseRulesCType[index] |= IS_MIME_SEP_BIT;
    }
    if (ParseRules::IsHttpFieldName(index)) {
      gTparseRulesCType[index] |= IS_HTTP_FIELD_NAME_BIT;
    }
    if (ParseRules::IsHttpFieldValue(index)) {
      gTparseRulesCType[index] |= IS_HTTP_FIELD_VALUE_BIT;
    }
  }

  // Write ParseRulesCType (bitmask table with binary representation)
  std::ofstream outputFile("ParseRulesCType");
  if (!outputFile) {
    std::cerr << "Error: Failed to open ParseRulesCType for writing." << std::endl;
    return 1;
  }
  for (uint16_t i = 0; i < 256; ++i) {
    outputFile << "/* " << std::setw(3) << i << " (" << (isprint(i) ? static_cast<char>(i) : '?') << ") */\t";
    outputFile << "0x" << std::hex << std::setw(8) << std::setfill('0') << gTparseRulesCType[i] << (i != 255 ? ",\t\t" : "\t\t");
    outputFile << "/* [" << uint_to_binary(gTparseRulesCType[i]) << "] */\n";
  }

  // Write ParseRulesCTypeToUpper (uppercase conversion table)
  {
    std::ofstream outputFile("ParseRulesCTypeToUpper");
    if (!outputFile) {
      std::cerr << "Error: Failed to open ParseRulesCTypeToUpper for writing." << std::endl;
      return 1;
    }
    for (uint16_t i = 0; i < 256; ++i) {
      outputFile << "(uint8_t)" << static_cast<unsigned>(gTparseRulesCTypeToUpper[i]) << (i != 255 ? ',' : ' ') << '\n';
    }
  }

  // Write ParseRulesCTypeToLower (lowercase conversion table)
  {
    std::ofstream outputFile("ParseRulesCTypeToLower");
    if (!outputFile) {
      std::cerr << "Error: Failed to open ParseRulesCTypeToLower for writing." << std::endl;
      return 1;
    }
    for (uint16_t i = 0; i < 256; ++i) {
      fp << "(uint8_t)" << static_cast<unsigned>(gTparseRulesCTypeToLower[i]) << (i != 255 ? ',' : ' ') << '\n';
    }
  }

  return (0);
}
