/**
 * @file CompileParseRules.cc
 *
 * @brief Build-time utility for generating ParseRules character classification tables.
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This standalone C++ program generates static lookup tables used by the
 * Traffic Server runtime for O(1) character classification and case conversion.
 * It is executed during the build process and is **not part of the runtime library**.
 *
 * The generated tables are written to the following files:
 *   - @c ParseRulesCType: Bitmask of character type flags (32-bit values).
 *   - @c ParseRulesCTypeToUpper: Uppercase conversion table (uint8_t values).
 *   - @c ParseRulesCTypeToLower: Lowercase conversion table (uint8_t values).
 *
 * These files are typically included as static data in @c ParseRules.cc.
 *
 * @note This tool uses modern C++ features, including:
 *       - @c std::string for type-safe string handling.
 *       - @c std::ofstream for RAII-based file I/O.
 *       -  Fixed-width integer types (@c uint8_t, @c uint32_t) for portability.
 *
 * @see ParseRules.h for character classification function declarations.
 * @see ParseRules.cc for runtime usage of generated tables.
 */

#include <cstdint>
#include <cstdio>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <string>

#include "tscore/ParseRules.h"

/**
 * @brief Placeholder for the character type bitmask table.
 *
 * This array is initialized to zero and serves as a template for the generated
 * @c ParseRulesCType table. It is **not used at runtime**.
 *
 * @note The actual populated table is generated by @c main() and written to
 *       the @c ParseRulesCType file.
 */
const uint32_t parseRulesCType[256] = {0};

/**
 * @brief Placeholder for the uppercase conversion table.
 *
 * This array is initialized to zero and serves as a template for the generated
 * @c ParseRulesCTypeToUpper table. It is **not used at runtime**.
 *
 * @note The actual populated table is generated by @c main() and written to
 *       the @c ParseRulesCTypeToUpper file.
 */
const uint8_t parseRulesCTypeToUpper[256] = {0};

/**
 * @brief Placeholder for the lowercase conversion table.
 *
 * This array is initialized to zero and serves as a template for the generated
 * @c ParseRulesCTypeToLower table. It is **not used at runtime**.
 *
 * @note The actual populated table is generated by @c main() and written to
 *       the @c ParseRulesCTypeToLower file.
 */
const uint8_t parseRulesCTypeToLower[256] = {0};

/**
 * @brief Working array for character type bitmasks.
 *
 * Temporary storage for computed character classification bitmasks.
 * Populated by @c main() and written to the @c ParseRulesCType output file.
 *
 * @note Each entry is a 32-bit bitmask where each bit represents a character
 *       classification (e.g., @c is_alpha_BIT, @c is_digit_BIT).
 */
uint32_t tparseRulesCType[256];

/**
 * @brief Working array for uppercase character conversion.
 *
 * Temporary storage for uppercase character mappings (0-255).
 * Populated by @c main() and written to the @c ParseRulesCTypeToUpper output file.
 */
uint8_t tparseRulesCTypeToUpper[256];

/**
 * @brief Working array for lowercase character conversion.
 *
 * Temporary storage for lowercase character mappings (0-255).
 * Populated by @c main() and written to the @c ParseRulesCTypeToLower output file.
 */
uint8_t tparseRulesCTypeToLower[256];

/**
 * @brief Convert a 32-bit unsigned integer to its binary string representation.
 *
 * Creates a 32-character string representing the binary value of the input,
 * with leading zeros. The string is in **big-endian format** (MSB first).
 *
 * @param u The 32-bit unsigned integer to convert.
 * @return @c std::string containing the 32-character binary representation.
 *         Example: @c uint_to_binary(5) returns @c "00000000000000000000000000000101".
 *
 * @note This function is **thread-safe** because it returns a new @c std::string
 *       by value (no shared static buffer).
 */
std::string
uint_to_binary(uint32_t u)
{
  std::string buf(32, '0');
  for (uint8_t i = 0; i < 32; i++) {
    if (u & (1U << (31 - i))) {
      buf[i] = '1';
    }
  }
  return buf;
}

/**
 * @brief Generates character classification lookup tables.
 *
 * This function performs the following steps:
 *
 * 1. For each ASCII character (0-255):
 *    - Initializes the working arrays (@c tparseRulesCType, @c tparseRulesCTypeToUpper,
 *      @c tparseRulesCTypeToLower).
 *    - Tests the character against all @c ParseRules classification functions.
 *    - Sets the corresponding bit in @c tparseRulesCType[i] for each matching classification.
 *    - Stores the uppercase/lowercase conversion values in @c tparseRulesCTypeToUpper
 *      and @c tparseRulesCTypeToLower.
 *
 * 2. Writes three output files using @c std::ofstream (RAII):
 *    - @c ParseRulesCType: Contains hexadecimal bitmask values and their binary
 *      representations. Format: C-style array initialization.
 *    - @c ParseRulesCTypeToUpper: Contains uppercase conversion values for each
 *      character. Format: @c (uint8_t)X,
 *    - @c ParseRulesCTypeToLower: Contains lowercase conversion values for each
 *      character. Format: @c (uint8_t)X,
 *
 * @return 0 on successful completion.
 *
 * @note The classification functions from @c ParseRules.h include:
 *       - **Character types**: @c is_char, @c is_alpha, @c is_digit, @c is_alnum,
 *         @c is_ctl, @c is_ws, @c is_hex, @c is_pchar, @c is_token, @c is_uri,
 *         @c is_sep, @c is_empty.
 *       - **Case types**: @c is_upalpha, @c is_loalpha.
 *       - **Safety/encoding**: @c is_safe, @c is_unsafe, @c is_reserved,
 *         @c is_unreserved, @c is_national.
 *       - **Special categories**: @c is_punct, @c is_tspecials, @c is_end_of_url.
 *       - **Whitespace variants**: @c is_spcr, @c is_splf, @c is_wslfcr, @c is_eow.
 *       - **HTTP/MIME**: @c is_http_field_name, @c is_http_field_value,
 *         @c is_mime_sep, @c is_control.
 *
 * @see ParseRules.h for detailed descriptions of each classification function.
 * @see ParseRules.cc for runtime usage of the generated tables.
 */
int
main()
{
  for (uint16_t i = 0; i < 256; i++) {
    tparseRulesCType[i]        = 0;
    tparseRulesCTypeToLower[i] = static_cast<uint8_t>(ParseRules::ink_tolower(i));
    tparseRulesCTypeToUpper[i] = static_cast<uint8_t>(ParseRules::ink_toupper(i));

    if (ParseRules::is_char(i)) {
      tparseRulesCType[i] |= is_char_BIT;
    }
    if (ParseRules::is_upalpha(i)) {
      tparseRulesCType[i] |= is_upalpha_BIT;
    }
    if (ParseRules::is_loalpha(i)) {
      tparseRulesCType[i] |= is_loalpha_BIT;
    }
    if (ParseRules::is_alpha(i)) {
      tparseRulesCType[i] |= is_alpha_BIT;
    }
    if (ParseRules::is_digit(i)) {
      tparseRulesCType[i] |= is_digit_BIT;
    }
    if (ParseRules::is_ctl(i)) {
      tparseRulesCType[i] |= is_ctl_BIT;
    }
    if (ParseRules::is_ws(i)) {
      tparseRulesCType[i] |= is_ws_BIT;
    }
    if (ParseRules::is_hex(i)) {
      tparseRulesCType[i] |= is_hex_BIT;
    }

    char cc = static_cast<char>(i);

    if (ParseRules::is_pchar(&cc)) {
      tparseRulesCType[i] |= is_pchar_BIT;
    }
    if (ParseRules::is_extra(i)) {
      tparseRulesCType[i] |= is_extra_BIT;
    }
    if (ParseRules::is_safe(i)) {
      tparseRulesCType[i] |= is_safe_BIT;
    }
    if (ParseRules::is_unsafe(i)) {
      tparseRulesCType[i] |= is_unsafe_BIT;
    }
    if (ParseRules::is_national(i)) {
      tparseRulesCType[i] |= is_national_BIT;
    }
    if (ParseRules::is_reserved(i)) {
      tparseRulesCType[i] |= is_reserved_BIT;
    }
    if (ParseRules::is_unreserved(i)) {
      tparseRulesCType[i] |= is_unreserved_BIT;
    }
    if (ParseRules::is_punct(i)) {
      tparseRulesCType[i] |= is_punct_BIT;
    }
    if (ParseRules::is_end_of_url(i)) {
      tparseRulesCType[i] |= is_end_of_url_BIT;
    }
    if (ParseRules::is_tspecials(i)) {
      tparseRulesCType[i] |= is_tspecials_BIT;
    }
    if (ParseRules::is_spcr(i)) {
      tparseRulesCType[i] |= is_spcr_BIT;
    }
    if (ParseRules::is_splf(i)) {
      tparseRulesCType[i] |= is_splf_BIT;
    }
    if (ParseRules::is_wslfcr(i)) {
      tparseRulesCType[i] |= is_wslfcr_BIT;
    }
    if (ParseRules::is_eow(i)) {
      tparseRulesCType[i] |= is_eow_BIT;
    }
    if (ParseRules::is_token(i)) {
      tparseRulesCType[i] |= is_token_BIT;
    }
    if (ParseRules::is_uri(i)) {
      tparseRulesCType[i] |= is_uri_BIT;
    }
    if (ParseRules::is_sep(i)) {
      tparseRulesCType[i] |= is_sep_BIT;
    }
    if (ParseRules::is_empty(i)) {
      tparseRulesCType[i] |= is_empty_BIT;
    }
    if (ParseRules::is_alnum(i)) {
      tparseRulesCType[i] |= is_alnum_BIT;
    }
    if (ParseRules::is_space(i)) {
      tparseRulesCType[i] |= is_space_BIT;
    }
    if (ParseRules::is_control(i)) {
      tparseRulesCType[i] |= is_control_BIT;
    }
    if (ParseRules::is_mime_sep(i)) {
      tparseRulesCType[i] |= is_mime_sep_BIT;
    }
    if (ParseRules::is_http_field_name(i)) {
      tparseRulesCType[i] |= is_http_field_name_BIT;
    }
    if (ParseRules::is_http_field_value(i)) {
      tparseRulesCType[i] |= is_http_field_value_BIT;
    }
  }

  // Write ParseRulesCType (bitmask table with binary representation)
  std::ofstream fp("ParseRulesCType");
  for (uint16_t i = 0; i < 256; ++i) {
    fp << "/* " << std::setw(3) << i << " (" << (isprint(i) ? static_cast<char>(i) : '?') << ") */\t";
    fp << "0x" << std::hex << std::setw(8) << std::setfill('0') << tparseRulesCType[i] << (i != 255 ? ",\t\t" : "\t\t");
    fp << "/* [" << uint_to_binary(tparseRulesCType[i]) << "] */\n";
  }

  // Write ParseRulesCTypeToUpper (uppercase conversion table)
  {
    std::ofstream fp("ParseRulesCTypeToUpper");
    for (uint16_t i = 0; i < 256; ++i) {
      fp << "(uint8_t)" << static_cast<unsigned>(tparseRulesCTypeToUpper[i]) << (i != 255 ? ',' : ' ') << '\n';
    }
  }

  // Write ParseRulesCTypeToLower (lowercase conversion table)
  {
    std::ofstream fp("ParseRulesCTypeToLower");
    for (uint16_t i = 0; i < 256; ++i) {
      fp << "(uint8_t)" << static_cast<unsigned>(tparseRulesCTypeToLower[i]) << (i != 255 ? ',' : ' ') << '\n';
    }
  }

  return (0);
}
