#! /usr/bin/env bash
#
#  Simple pre-commit hook script, enforcing clang-format on our tree
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

GIT_TOP="$(git rev-parse --show-toplevel)"
source "$GIT_TOP/tools/clang-format.sh"

case $(uname -s) in
Darwin)
    FORMAT=${FORMAT:-${ROOT}/clang-format/clang-format.osx}
    ;;
Linux)
    FORMAT=${FORMAT:-${ROOT}/clang-format/clang-format.linux}
    ;;
*)
    echo "Leif needs to build a clang-format for $(uname -s)"
    exit 2
esac

# If there is no clang-format in our git repo, then try from git config
[ ! -x "$FORMAT" ] && FORMAT=$(git config clangFormat.binary)

# Make sure we have some clang-format executable...
if [ ! -x "$FORMAT" ]; then
    echo "No clang-format found"
    exit 1
fi

source "$GIT_TOP/tools/autopep8.sh"
if [ ! -d ${AUTOPEP8_VENV} ]
then
    echo "Run \"make autopep8\""
    exit 1
fi
source ${AUTOPEP8_VENV}/bin/activate


# Where to store the patch
clang_patch_file=$(mktemp -t clang-format.XXXXXXXXXX)
autopep8_patch_file=$(mktemp -t autopep8.XXXXXXXXXX)
trap "rm -f $clang_patch_file $autopep8_patch_file" 0 1 2 3 5 15

# Loop over all files that are changed, and produce a diff file
git diff-index --cached --diff-filter=ACMR --name-only HEAD | grep -vE "lib/yamlcpp" | while read file; do
    case "$file" in
	*.cc | *.c | *.h | *.h.in)
	    ${FORMAT} "$file" | diff -u "$file" - >> "$clang_patch_file"
	    ;;
        # Keep this list of Python extensions the same with the list of
        # extensions searched for in the toosl/autopep8.sh script.
        *.py | *.cli.ext | *.test.ext)
            autopep8 \
                --ignore-local-config \
                --exclude ${GIT_TOP}/lib/yamlcpp \
                --max-line-length 132 \
                --aggressive \
                --aggressive \
                --diff \
                "$file" >> "$autopep8_patch_file"
    esac
done

if [ -s "$clang_patch_file" ] ; then
    echo "The commit is not accepted, because clang-format does not match current"
    echo "requirements. Easiest to fix this is to run:"
    echo
    echo "    $ make -j clang-format"
    exit 1
else
    echo "This commit complies with the current clang-format indentation rules."
    echo
fi


if [ -s "$autopep8_patch_file" ] ; then
    echo "The commit is not accepted because autopep8 reports issues with it."
    echo "The easiest way to fix this is to run:"
    echo
    echo "    $ make autopep8"
    exit 1
else
    echo "This commit complies with the current autopep8 formatting rules."
    echo
fi

# Cleanup before exit
deactivate
rm -f "$clang_patch_file" "$autopep8_patch_file"
exit 0
