#!/bin/bash -e

#  Copyright (C) 2022 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions
#  and limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0

trap 'echo " $! ERROR $BASH_COMMAND">&2' err
while ndctl create-namespace --mode=devdax --map=mem --name=trafficserver; do : ; done
trap "ipmctl create -goal PersistentMemoryType=AppDirectNotInterleaved MemoryMode=0 && shutdown -r" exit
shopt -s nullglob

function append {
grep "$2" "$1" || echo "$2" >>"$1"
}

for DAX in /dev/dax[0-9].[0-9] ; do
	test -c $DAX
	daxctl reconfigure-device ${DAX##*/} --mode=devdax > >(
		while IFS=":" read N V ; do case $N in
		'    "size"') append /usr/local/etc/trafficserver/storage.config "$DAX $(bc <<< ${V%,}+8192)" ;;
		'    "mode"') [ ${V//\"/} = "devdax" ] ;;
		esac ; done )
	trap exit
done

