
find_path(PCRE_INCLUDE_DIR NAMES pcre.h PATH_SUFFIXES pcre)
find_library(PCRE_LIBRARY NAMES pcre)

message(PCRE_INCLUDE_DIR=${PCRE_INCLUDE_DIR})
message(PCRE_LIBRARY=${PCRE_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE DEFAULT_MSG PCRE_LIBRARY PCRE_INCLUDE_DIR)

if(PCRE_FOUND)
    SET(PCRE_LIBRARIES ${PCRE_LIBRARY})
    SET(PCRE_INCLUDE_DIRS ${PCRE_INCLUDE_DIR})
else(PCRE_FOUND)
    SET(PCRE_LIBRARIES)
    SET(PCRE_INCLUDE_DIRS)
endif(PCRE_FOUND)
