#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

from pathlib import Path

from tools.uranium.services import ATS, ATSFactory, OriginServer, ProcessService, ServiceFactory

TEST_DIRECTORY = Path(__file__).parent

LARGE_TLS_POST__header_count = 378


def configure_origin(services: ServiceFactory) -> OriginServer:
    """Expect the exact large POST generated by ssl-post.

    :param services: Factory owning support services and their cleanup.
    """

    origin = services.origin("origin")
    headers = "POST /post HTTP/1.1\r\nHost: www.example.com\r\nContent-Length:1000\r\n"
    headers += "".join(f"header{index}:{index}\r\n" for index in range(LARGE_TLS_POST__header_count))
    origin.add_response(
        {
            "headers": headers + "\r\n",
            "body": "0" * 1000
        },
        {
            "headers":
                (
                    "HTTP/1.1 200 OK\r\nServer: microserver\r\nConnection: close\r\n"
                    "Cache-Control: max-age=3600\r\nContent-Length: 2\r\n\r\n"),
            "body": "ok",
        },
    )
    return origin


def configure_ats(ats_factory: ATSFactory, *, _origin: OriginServer) -> ATS:
    """Terminate TLS and forward the POST to the microserver.

    :param _origin: Test-local origin configured by the test.
    :param ats_factory: Factory for isolated Traffic Server instances.
    """

    ats = ats_factory.create("ts", enable_tls=True)
    ats.add_default_ssl_files()
    ats.remap_config.add_line(f"map / http://127.0.0.1:{_origin.port}")
    ats.ssl_multicert_config.add_lines(
        (
            "ssl_multicert:",
            '  - dest_ip: "*"',
            "    ssl_cert_name: server.pem",
            "    ssl_key_name: server.key",
        ))
    ats.records.update(
        {
            "proxy.config.exec_thread.autoconfig.scale": 1.0,
            "proxy.config.diags.debug.enabled": 1,
            "proxy.config.diags.debug.tags": "ssl",
        })
    return ats


def configure_client(services: ServiceFactory, *, _ats: ATS) -> ProcessService:
    """Locate the generated concurrent TLS POST driver.

    :param _ats: Test-local ats configured by the test.
    :param services: Factory owning support services and their cleanup.
    """

    client = services.resolve_path("{AtsBuildUraniumTestsDir}/tls/ssl-post")
    return services.process(
        "client",
        (client, "127.0.0.1", "40", str(LARGE_TLS_POST__header_count), str(_ats.https_port)),
    )


def test_tls(ats_factory: ATSFactory, services: ServiceFactory) -> None:
    """ATS handles concurrent large-header TLS POST requests.

    :param ats_factory: Factory for isolated Traffic Server instances.
    :param services: Factory owning support services and their cleanup.
    """
    _origin = configure_origin(services)
    _ats = configure_ats(ats_factory, _origin=_origin)
    _client = configure_client(services, _ats=_ats)

    _origin.start()
    _ats.start()
    result = _client.run()
    assert result.returncode == 0, result.output
    assert result.stdout == (TEST_DIRECTORY / "gold" / "ssl-post.gold").read_text()
    assert _origin.is_running
