/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
Package voluspa generates ATS configuration files for a CDN from a set of
simple YAML files that express the desired behaviour of each of the hosted properties.

For example, given this property specification:

    schema_version: 1
    owner: Web Group
    rcpt: httpbin

    mappings:
    - alias:
        - httpbin.example.com
        origin: https://httpbin.origin.example.com
        schemes: [http, https]

    rules:
      default:
        priority: background
        origin_host_header: origin
        deny_methods: [ CONNECT ]

Voluspa will generate the corresponding ATS configuration files in the
specified output directory.  A `httpbin/httpbin.config` file:

    # Code generated by Voluspa. DO NOT EDIT.
    map http://httpbin.example.com \
        https://https://httpbin.origin.example.com \
        @plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=0 \
        @plugin=header_rewrite.so @pparam=httpbin/hdrs.config \
        @plugin=propstats.so @pparam=--prefix=proxy.domain.httpbin \
        @action=deny @method=CONNECT

and a `httpbin/hdrs.config` file:

    # Code generated by Voluspa. DO NOT EDIT.
    cond %{REMAP_PSEUDO_HOOK}
        set-header @ReceiptService "httpbin{{hosttype}}"
    cond %{REMAP_PSEUDO_HOOK}
        set-conn-dscp 8

The voluspa package enables fine control over the generation of configurations
and enables functionality to be extended via "adapters".

The distribution includes a `voluspa` command line utility that loads a set of
YAML files and generates the ATS configuration files using code like this:

    import (
        "flag"
        "fmt"
        "log"

        "github.com/apache/trafficserver/tools/voluspa"
        _ "github.com/apache/trafficserver/tools/voluspa/adapters"
    )

    v, err := voluspa.NewVoluspa()
    if err != nil {
        log.Fatalf("voluspa: %s", err)
    }

    // Load the YAML config file for each property in the CDN
    for _, filename := range flag.Args() {
        err = v.AddConfig(filename)
        if err != nil {
            log.Fatalf("%s", err) // err includes the filename
        }
    }

    // Validate the set of configurations, individually and as a whole
    if err = v.Validate(true); err != nil {
        log.Fatalf("%s", err)
    }

    // Generate the resulting ATS config files
    if err = v.WriteAllATSFiles(); err != nil {
        log.Fatalf("%s", err)
    }

*/
package voluspa
